#!/bin/bash
set -e -x

# ========================================================
# Nokia 6.1 (PL2 / TA-1089) keepQASSA 2.4 (Android 10 Q)
# ========================================================
WORKDIR="/crave-devspaces/qassa_build"
mkdir -p "$WORKDIR" && cd "$WORKDIR"
echo "=== Starting Nokia 6.1 (PL2) keepQASSA 2.4 (Android 10 Q) Build ==="

# Repo
if ! command -v repo >/dev/null 2>&1; then
    mkdir -p "$HOME/bin" && curl -L https://storage.googleapis.com/git-repo-downloads/repo -o "$HOME/bin/repo" && chmod a+rx "$HOME/bin/repo" && export PATH="$HOME/bin:$PATH"
fi
# ========================================================
# PHASE 1: EXECUTION, MEMORY & COMPILER GUARDS
# ========================================================
export GOMEMLIMIT=8GiB
export GOGC=50
export _JAVA_OPTIONS="-Xmx6g"
export SOONG_ALLOW_MISSING_DEPENDENCIES=true
export WITHOUT_CHECK_API=true
export SKIP_ABI_CHECKS=true
export SELINUX_IGNORE_NEVERALLOWS=true
export WITH_GAPPS=false
export BUILD_USERNAME=Zoro-15 BUILD_HOSTNAME=crave
# ========================================================
# PHASE 2: PRE-FLIGHT CLEANUP (SAFE FOR CRAVE)
# ========================================================
echo "--> Cleaning stale local manifests and device trees..."
# Clean previous device manifests/repos
rm -rf .repo/local_manifests device/nokia/PL2 device/nokia/sdm660-common kernel/nokia/sdm660 vendor/nokia

# Init + local manifest
echo "--> Initializing keepQASSA 2.4 (Android 10 Q) manifest..."
repo init --depth=1 -u https://github.com/keepQASSA/manifest -b Q --git-lfs

mkdir -p .repo/local_manifests
cat > .repo/local_manifests/nokia.xml <<'XML'
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <remote name="zoro" fetch="https://github.com/Zoro-15" revision="lineage-17.1 - what should be here according to qassa 2.4_5 "/>
  <project path="device/nokia/PL2" name="android_device_nokia_PL2" remote="zoro"/>
  <project path="device/nokia/sdm660-common" name="android_device_nokia_sdm660-common" remote="zoro"/>
  <project path="kernel/nokia/sdm660" name="android_kernel_nokia_sdm660" remote="zoro"/>
  <project path="vendor/nokia" name="proprietary_vendor_nokia" remote="zoro"/>
</manifest>
XML


# Crave resync + source sync
if [ -f /usr/bin/resync ]; then /usr/bin/resync; else /opt/crave/resync.sh; fi
repo sync -c --force-sync --force-remove-dirty --no-tags --no-clone-bundle -j$(nproc)

# Legacy ncurses dependencies
if [ ! -f /usr/lib/x86_64-linux-gnu/libncurses.so.5 ] || [ ! -f /usr/lib/x86_64-linux-gnu/libtinfo.so.5 ]; then
    sudo apt-get update -qq 2>/dev/null || true
    sudo apt-get install -y -qq wget curl 2>/dev/null || true
    P="http://archive.ubuntu.com/ubuntu/pool/universe/n/ncurses"
    T=$(curl -sL "$P/" | grep -oE 'libtinfo5_[^"<> ]+_amd64\.deb' | sort -V | tail -1)
    N=$(curl -sL "$P/" | grep -oE 'libncurses5_[^"<> ]+_amd64\.deb' | sort -V | tail -1)
    [ -n "$T" ] && [ -n "$N" ] && wget -q "$P/$T" -O /tmp/tinfo.deb && wget -q "$P/$N" -O /tmp/ncurses.deb && sudo apt-get install -y /tmp/tinfo.deb /tmp/ncurses.deb && rm -f /tmp/tinfo.deb /tmp/ncurses.deb || true
fi


# Verify required repos
test -d device/nokia/PL2 && test -d device/nokia/sdm660-common && test -d kernel/nokia/sdm660 && test -d vendor/nokia

# ccache
if [ -x prebuilts/misc/linux-x86/ccache/ccache ]; then
    export USE_CCACHE=1 CCACHE_EXEC="$PWD/prebuilts/misc/linux-x86/ccache/ccache" CCACHE_DIR="$HOME/.ccache"
    "$CCACHE_EXEC" -M 50G 2>/dev/null || true
fi

# Build
set +e
source build/envsetup.sh
set -e

lunch qassa_PL2-userdebug
make installclean
echo "--> Compiling keepQASSA 2.4 target image..."
mka qassa -j$(nproc --all)

# =======================================================================================================================================================================
# PHASE 6: ARTIFACT DISCOVERY, CHECKSUM & CLOUD UPLOAD
# ========================================================

echo "========================================================"
echo "--> Locating keepQASSA ROM artifact..."
echo "========================================================"

PRODUCT_OUT="$PWD/out/target/product/PL2"

if [ ! -d "$PRODUCT_OUT" ]; then
    echo "ERROR: Product output directory not found:"
    echo "$PRODUCT_OUT"
    exit 1
fi

# Find ROM ZIPs generated by the build.
# Exclude OTA metadata/checksum files.
ROM_ZIP=$(find "$PRODUCT_OUT" -maxdepth 1 -type f -name "*.zip" \
    ! -name "*.json" \
    ! -name "*.sha256sum" \
    -printf "%T@ %p\n" 2>/dev/null \
    | sort -n \
    | tail -1 \
    | cut -d' ' -f2-)

if [ -z "$ROM_ZIP" ] || [ ! -f "$ROM_ZIP" ]; then
    echo "ERROR: No ROM ZIP found in:"
    echo "$PRODUCT_OUT"
    echo
    echo "Available files:"
    find "$PRODUCT_OUT" -maxdepth 1 -type f -printf '%f\n' | sort
    exit 1
fi

ROM_NAME="$(basename "$ROM_ZIP")"
ROM_DIR="$(dirname "$ROM_ZIP")"

echo "--> ROM found:"
echo "    $ROM_NAME"

echo
echo "--> ROM size:"
ls -lh "$ROM_ZIP"

# --------------------------------------------------------
# SHA-256
# --------------------------------------------------------

SHA_FILE="${ROM_ZIP}.sha256sum"

echo
echo "--> Calculating SHA-256..."

sha256sum "$ROM_ZIP" > "$SHA_FILE"

echo "--> SHA-256:"
cat "$SHA_FILE"

# --------------------------------------------------------
# Upload ROM to temp.sh
# --------------------------------------------------------

echo
echo "========================================================"
echo "--> Uploading ROM to temp.sh..."
echo "========================================================"

TEMP_URL_FILE="$PRODUCT_OUT/${ROM_NAME}.temp-sh-url.txt"

set +e

TEMP_URL=$(
    curl --fail --silent --show-error \
        -F "file=@${ROM_ZIP}" \
        https://temp.sh/upload
)

UPLOAD_STATUS=$?

set -e

if [ "$UPLOAD_STATUS" -ne 0 ] || [ -z "$TEMP_URL" ]; then
    echo
    echo "WARNING: temp.sh upload failed."
    echo "The ROM build itself remains successful."
    echo "You can still use Crave pull to retrieve the artifact."
else
    echo "$TEMP_URL" | tee "$TEMP_URL_FILE"

    echo
    echo "========================================================"
    echo "--> TEMP.SH DOWNLOAD URL"
    echo "========================================================"
    echo "$TEMP_URL"
    echo "========================================================"
fi

# --------------------------------------------------------
# Final artifact summary
# --------------------------------------------------------

echo
echo "========================================================"
echo "BUILD ARTIFACT SUMMARY"
echo "========================================================"
echo "ROM:"
echo "  $ROM_ZIP"
echo
echo "SHA256:"
echo "  $SHA_FILE"
echo
echo "TEMP.SH URL FILE:"
echo "  $TEMP_URL_FILE"
echo "========================================================"
